### ISSUE TITLE
How to add this to my Flutter project? (Error: "Could not find a file named "pubspec.yaml" in")

### ISSUE THREAD

**Issue by yasinarik** [xioxin/lab_sound_flutter#5]
Hi @xioxin! Thanks for creating this repo and making it public.

Can I use it in my projects? If yes, **how** can I use it?

I have searched pub.dev but couldn't find a package of this repo.
####  I have tried adding it to my project's `pubspec.yaml` file like this:

```yaml
  lab_sound_flutter:
    git:
      url: https://github.com/xioxin/lab_sound_flutter   #also with .git suffix
      ref: main   #or a commit hash like f89e1a5
```

#### However, I am getting this error:
```text
Could not find a file named "pubspec.yaml" in 
"/Users/yasinarik/.pub-cache/git/lab_sound_flutter-f89e1a56a223e3f61b3b1bda51818578be01e237".

pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/yasinarik/.pub-cache/git/lab_sound_flutter-f89e1a56a223e3f61b3b1bda51818578be01e237".)
exit code 66
```

Could you please help?
